In [1]:
import pywt

In [2]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


In [5]:
batch_size = 256
total_batch = int(mnist.train.num_examples/batch_size)
print("total_batch ", total_batch)

for i in range(total_batch):
    batch_xs, batch_ys = mnist.train.next_batch(batch_size)

total_batch  214


In [10]:
mnist.train.num_examples

55000

In [9]:
from pywt import wavedec
coeffs = wavedec(batch_xs, 'haar', level=2)
print(coeffs[0])
print(coeffs[1])
print(coeffs[2])
from pywt import waverec
reconstruct = waverec(coeffs, 'haar')
print(reconstruct)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [2]:
x_t = [6.65, 7.15, 6.31, 5.94, 4.89, 4.95, 5.05, 5.39, 4.54, 5.01, 4.96, 5.08, 5.07, 4.93, 200, 5.12, 5.19, 5.86, 6.45, 6.44, 7.59, 8.59, 10.44, 11.49, 9.96, 9.91, 11.04, 12.19, 12.14, 12.09, 11.32, 12.1]
x_t2 = [6.65, 7.15, 6.31, 5.94, 4.89, 104.95, 5.05, 5.39, 4.54, 5.01, 4.96, 5.08, 5.07, 4.93, 20, 5.12, 5.19, 5.86, 6.45, 6.44, 7.59, -8.59, 10.44, 11.49, 9.96, 9.91, 11.04, 12.19, -12.14, 12.09, 11.32, 12.1, 6.5, 7.15, 6.31, 5.94, 4.89, 2.95, 5.05, 5.39, 4.54, 5.01, 4.96, 5.08, 5.07, 4.93, 2, 5.12, 5.19, 6.65, 7.15, 6.31, 5.94, 4.89, 1004.95, 5.05, 5.39, 4.54, 5.01, 4.96, 5.08, 5.07, 4.93, 20, 5.12, 5.19, 6.65, 7.15, 6.31, 5.94, 4.89, 1.95, 5.05, 5.39, 4.54, 5.01, 4.96, 5.08, 5.07, 4.93, 200, 5.12, 5.19, 2.5, 7.15, 6.31, 5.94, 4.89, 0.95, 5.05, 5.39, 4.54, 5.01, 4.96, 5.08, 5.07, 4.93, 3, 5.12, 5.19]

In [3]:
wavelet = pywt.Wavelet('haar')  # Basis Wavelet
phi, psi, x = wavelet.wavefun(level=5)

array([0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.])

In [ ]:
from pywt import Wavelet, integrate_wavelet

In [ ]:
[int_psi, x_grid] = integrate_wavelet(wavelet, precision=5)

In [ ]:
x_grid

## Single level DWT  
x_t : 1 X 30 --> (1 X 15) (1 X 15)

In [22]:
(cA, cD) = pywt.dwt(x_t2, 'haar')
print(cA)
print(cD)

[ 1.22895159e+02  8.66205807e+00  7.14064712e+02  7.38219480e+00
  6.75286976e+00  7.09935208e+00  7.07106781e+00  1.45041743e+02
  7.81352993e+00  9.11460641e+00  1.14409877e+01  1.55068517e+01
  1.40502117e+01  1.64260905e+01 -3.53553391e-02  1.65604408e+01]
[ 1.12783532e+02  2.61629509e-01 -7.07149208e+02 -2.40416306e-01
 -3.32340187e-01 -8.48528137e-02  9.89949494e-02  1.37800970e+02
 -4.73761543e-01  7.07106781e-03 -7.07106781e-01 -7.42462120e-01
  3.53553391e-02 -8.13172798e-01 -1.71331973e+01 -5.51543289e-01]


In [ ]:
len(x_t), len(cA)

## 2-level decomposition  
x_t : 1 X 30 --> (1 X 8) (1 X 8) (1 X 15)

In [5]:
from pywt import wavedec
coeffs = wavedec(x_t2, 'haar', level=2)

In [6]:
print(coeffs[0])
print(coeffs[1])
print(coeffs[2])

[ 13.025  60.14    9.795  17.56   11.97   10.465  21.55   11.685  12.95
   9.14    9.795   8.56   12.65  510.415   9.95   17.54   12.055   9.545
   9.995  10.02  106.405  12.145   7.965  10.06    9.12 ]
[ 7.75000e-01  4.97000e+01 -2.45000e-01 -7.56000e+00 -9.20000e-01
 -1.14650e+01 -1.68000e+00 -1.17350e+01  7.00000e-01 -1.30000e+00
 -2.45000e-01  1.44000e+00 -8.10000e-01 -4.99585e+02 -2.00000e-02
 -7.39000e+00 -1.74500e+00  2.70500e+00  4.45000e-01  2.00000e-02
  9.87150e+01  1.31500e+00 -1.96500e+00 -9.00000e-02 -1.19000e+00]
[-3.53553391e-01  2.61629509e-01 -7.07531045e+01 -2.40416306e-01
 -3.32340187e-01 -8.48528137e-02  9.89949494e-02  1.05217489e+01
 -4.73761543e-01  7.07106781e-03  1.14409877e+01 -7.42462120e-01
  3.53553391e-02 -8.13172798e-01 -1.71331973e+01 -5.51543289e-01
 -4.59619408e-01  2.61629509e-01  1.37178716e+00 -2.40416306e-01
 -3.32340187e-01 -8.48528137e-02  9.89949494e-02 -2.20617316e+00
 -1.03237590e+00  5.93969696e-01  7.42462120e-01  7.07036071e+02
  6.0104076

In [25]:
import numpy as np
coeffs[-2] == np.zeros_like(coeffs[-2])

array([False, False, False, False, False, False, False, False])

## 2-level reconstruction

In [7]:
from pywt import waverec
reconstruct = waverec(coeffs, 'haar')

In [8]:
reconstruct

array([ 6.65000e+00,  7.15000e+00,  6.31000e+00,  5.94000e+00,
        4.89000e+00,  1.04950e+02,  5.05000e+00,  5.39000e+00,
        4.54000e+00,  5.01000e+00,  4.96000e+00,  5.08000e+00,
        5.07000e+00,  4.93000e+00,  2.00000e+01,  5.12000e+00,
        5.19000e+00,  5.86000e+00,  6.45000e+00,  6.44000e+00,
        7.59000e+00, -8.59000e+00,  1.04400e+01,  1.14900e+01,
        9.96000e+00,  9.91000e+00,  1.10400e+01,  1.21900e+01,
       -1.21400e+01,  1.20900e+01,  1.13200e+01,  1.21000e+01,
        6.50000e+00,  7.15000e+00,  6.31000e+00,  5.94000e+00,
        4.89000e+00,  2.95000e+00,  5.05000e+00,  5.39000e+00,
        4.54000e+00,  5.01000e+00,  4.96000e+00,  5.08000e+00,
        5.07000e+00,  4.93000e+00,  2.00000e+00,  5.12000e+00,
        5.19000e+00,  6.65000e+00,  7.15000e+00,  6.31000e+00,
        5.94000e+00,  4.89000e+00,  1.00495e+03,  5.05000e+00,
        5.39000e+00,  4.54000e+00,  5.01000e+00,  4.96000e+00,
        5.08000e+00,  5.07000e+00,  4.93000e+00,  2.000

In [ ]:
direct_reconstruct = pywt.upcoef()

In [ ]:
orth_filter_bank = pywt.orthogonal_filter_bank(x_t)

In [ ]:
orth_filter_bank